const fs=require('fs'),assert=require('assert');
const {JSDOM}=require('./dependencies.cjs').load('jsdom');
const defaults=JSON.parse(fs.readFileSync('cabinet_dev/defaults.json'));
let html=fs.readFileSync('cabinet_work/VGD_Cabinet/VGD_Cabinet_UI.html','utf8');
for(const [key,data]of [['default_json',defaults],['initial_json',defaults],['presets_json',{}]])html=html.replace('#{'+key+'}',()=>JSON.stringify(JSON.stringify(data)).replace(/</g,'\\u003c'));
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://vgd.test',beforeParse(w){w.calls=[];w.sketchup=new Proxy({},{get:(_,k)=>data=>w.calls.push({action:k,data})});}});
const w=dom.window,d=w.document;
(async()=>{try{
  await new Promise(r=>setTimeout(r,650));
  const cases=JSON.parse(fs.readFileSync('outputs/description_cases.json'));
  w.receiveDescriptionContract({example:cases[0].packet,defaults,enums:{}});
  w.selectPage('description');w.showDescriptionPrompt();assert(d.getElementById('description_prompt').value.includes('THÔNG SỐ MẶC ĐỊNH'));
  w.insertDescriptionExample();assert(JSON.parse(d.getElementById('description_text').value).parameters.w===800);
  w.updateFormFromRuby({...defaults,__target_pid:'42',__model_guid:'model'});
  const before=w.getFormData(),calls=w.calls.length;
  w.checkDescription();let call=w.calls.at(-1);assert.equal(call.action,'preview_description');
  let id=call.data.request_id;
  w.receiveDescriptionPreview(id-1,cases[0].result);assert(d.getElementById('btn_description_apply').disabled);
  w.receiveDescriptionPreview(id,cases[0].result);assert(!d.getElementById('btn_description_apply').disabled);
  assert.deepStrictEqual(w.getFormData(),before);assert.equal(w.calls.length,calls+1);
  w.applyDescription();assert.equal(w.calls.at(-1).action,'apply_description');
  for(const {packet,result}of cases){
    w.applyDescriptionDraft(result.parameters,result.unsupported_features);
    const p=w.getFormData();
    assert.equal(p.__target_pid,null);assert(d.getElementById('btn_update').disabled);
    assert(!d.getElementById('live_update').checked);
    w.updateFormFromRuby({...defaults,__target_pid:'stale',w:999});assert.equal(w.getFormData().w,packet.parameters.w,'Late selection overwrote draft');
    for(const [k,v]of Object.entries(packet.parameters))assert.deepStrictEqual(p[k],result.parameters[k],'Validated setting changed: '+k);
    for(const [k,v]of Object.entries(result.parameters))assert.deepStrictEqual(p[k],v,'Validated round-trip changed: '+k);
    w.placeCabinet();assert.equal(w.calls.at(-1).action,'create_cabinet');
  }
  w.applyDescriptionDraft({...cases[0].result.parameters,shelf_depth_clearance:9.5});assert.equal(w.getFormData().shelf_depth_clearance,9.5);
  const partial=cases.at(-1);
  d.getElementById('description_text').value=JSON.stringify(partial.packet);
  w.receiveDescriptionPreview(id,partial.result);
  assert(d.getElementById('btn_description_apply').disabled);
  assert(!d.getElementById('btn_description_partial').hidden&&!d.getElementById('btn_description_partial').disabled);
  const count=w.calls.length;let question='';w.confirm=text=>{question=text;return false;};w.applyDescription(true);
  assert.equal(w.calls.length,count,'Cancelled partial sent callback');assert(question.includes('2200')&&question.includes('KHÔNG tự trừ')&&question.includes(partial.packet.unsupported_features[3]));
  w.confirm=()=>true;w.applyDescription(true);let approval=w.calls.at(-1);
  assert.equal(approval.action,'apply_description');assert.equal(approval.data.allow_partial,true);
  assert.deepStrictEqual(JSON.parse(JSON.stringify(approval.data.acknowledged_features)),partial.packet.unsupported_features);
  w.applyDescriptionDraft(partial.result.parameters,partial.result.unsupported_features);
  assert(!d.getElementById('description_draft_notice').hidden&&d.getElementById('description_draft_notice').textContent.includes('4 chi tiết'));
  assert.equal(w.getFormData().w,2200);assert.equal(w.getFormData().h_top,580);
  w.placeCabinet();assert.equal(w.calls.at(-1).data.w,2200);
  const evil={...cases[0].result,assumptions:['<img src=x onerror=alert(1)>'],unsupported_features:['complex'],can_apply:false};
  w.receiveDescriptionPreview(id,evil);assert(!d.querySelector('#description_review img'));assert(d.getElementById('btn_description_apply').disabled);
  w.invalidateDescriptionPreview();w.receiveDescriptionPreview(id,cases[0].result);assert(d.getElementById('btn_description_apply').disabled);
  assert(d.getElementById('btn_description_partial').disabled&&d.getElementById('btn_description_partial').hidden);
  w.returnToSelectedCabinet();assert.equal(w.calls.at(-1).action,'leave_description_draft');
  w.leaveDescriptionDraft();w.updateFormFromRuby({...defaults,__target_pid:'42'});assert(!d.getElementById('btn_update').disabled);
  assert(d.getElementById('description_draft_notice').hidden);
  await new Promise(r=>setTimeout(r,1100));
  assert(!w.calls.some(c=>c.action==='update_cabinet'||c.action==='save_preset'),'Import caused live update/save');
  console.log('PASS description DOM: full-parameter round-trip 10 cases; partial button, cancel/confirm/exact acknowledgment, width warning, persistent draft notice, edited approval invalidation, placement, no update/preset write');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1});
